#!/usr/bin/env php
<?php

var_dump($_SERVER);die();

require 'utils.php';

PHP_CodeSniffer_Yii2_GitHook\Utils::readProjectConfig();
PHP_CodeSniffer_Yii2_GitHook\Utils::replaceArgv("standard encoding colors ignore_warnings progress extensions *");
$vendorDir = PHP_CodeSniffer_Yii2_GitHook\Utils::getVendorDir();

echo "Running Code Sniffer...";

require "{$vendorDir}/squizlabs/php_codesniffer/CodeSniffer/CLI.php";

$cli = new PHP_CodeSniffer_CLI();
$cli->runphpcs();
