#!/usr/bin/env php
<?php

require 'utils.php';

$utils = new PHP_CodeSniffer_Yii2_GitHook\Utils();
$utils->replaceArgv('standard encoding colors ignore_warnings progress extensions ignore *');

echo "Running Code Sniffer...\n";

require "{$utils->getVendorDir()}/squizlabs/php_codesniffer/CodeSniffer/CLI.php";

$cli = new PHP_CodeSniffer_CLI();
$cli->runphpcs();
