#!/bin/sh

STANDARD="Yii2"
ENCODING="utf-8"
IGNORE_WARNINGS=
PROGRESS=
COLORS=Y

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
VENDOR="$PROJECT/vendor";

if [ "$IGNORE_WARNINGS" != "" ]
then
  IGNORE_WARNINGS="-n"
else
  IGNORE_WARNINGS=""
fi

if [ "$PROGRESS" != "" ]
then
  PROGRESS="-p"
else
  PROGRESS=""
fi

if [ "$COLORS" != "" ]
then
  COLORS="--runtime-set colors 1"
else
  COLORS="--runtime-set colors 0"
fi

if [ "$STANDARD" = "Yii2" ]
then
  STANDARD="$VENDOR/yiisoft/yii2-coding-standards/Yii2"
fi

# JS files

STAGED_FILES_CMD=`git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.js`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
  oIFS=$IFS
  IFS='
  '
  SFILES="$1"
  IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

for FILE in $SFILES
do
  FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
  echo "Running Code Sniffer for JS..."
  $VENDOR/bin/phpcs --standard=$STANDARD --encoding=$ENCODING $COLORS $IGNORE_WARNINGS $PROGRESS $FILES
  if [ $? != 0 ]
  then
    echo "Fix the error before commit."
    exit 1
  fi
fi

# PHP files

STAGED_FILES_CMD=`git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
  oIFS=$IFS
  IFS='
  '
  SFILES="$1"
  IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
  php -l -d display_errors=0 $PROJECT/$FILE
  if [ $? != 0 ]
  then
    echo "Fix the error before commit."
    exit 1
  fi
  FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
  echo "Running Code Sniffer for PHP..."
  $VENDOR/bin/phpcs --standard=$STANDARD --encoding=$ENCODING $COLORS $IGNORE_WARNINGS $PROGRESS $FILES
  if [ $? != 0 ]
  then
    echo "Fix the error before commit."
    exit 1
  fi
fi

exit $?